version: 2

jobs:
  m225_php71: &php71-base
    docker:
      - image: circleci/php:7.1-apache-node-browsers
      - image: circleci/mysql:5.7
        environment:
          MYSQL_PASSWORD: mage
          MYSQL_USER: mage
          MYSQL_DATABASE: magento
          MYSQL_ROOT_PASSWORD: docker
    environment:
      MAGENTO_VERSION: "2.2.5"
    working_directory: ~/tnw_extension
    steps:
      - checkout
      - run:
          name: Checkout related modules
          command: |
            for moduleName in Salesforce SForceBusiness; do
              git clone git@github.com:PowerSync/TNW_$moduleName.git $moduleName
              cd $moduleName
              branchExists=(`git branch -a|grep $CIRCLE_BRANCH`);

              echo $branchExists;

              if test -z "$branchExists"
              then
                git checkout $CIRCLE_BRANCH;
              else
                git checkout develop;
              fi

              cd ..
            done

      - run:
          name: Install System Package
          command: |
            sudo apt-get update
            sudo apt install -y libicu-dev libxml2-dev libxslt1-dev zlib1g-dev libmcrypt-dev libfreetype6-dev libjpeg62-turbo-dev libpng-dev
      - run:
          name: Install PHP extension
          command: |
            sudo docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
            sudo docker-php-ext-install -j$(nproc) intl soap xsl zip mcrypt pdo pdo_mysql gd gettext mbstring bcmath
      - run:
          name: Configure PHP
          command: |
            echo "memory_limit = 2G" | sudo tee --append /usr/local/etc/php/conf.d/memory.ini
            php -i
      - run:
          name: Permissions
          command: |
            cd /var/www/
            sudo chown -R circleci:circleci html
      - run:
          name: Get Magento Code Quality Tool
          command: |
            cd /var/www/html/
            git clone https://github.com/magento/marketplace-eqp magento-coding-standard
            cd magento-coding-standard
            composer install
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: Installing Magento CE
          command: |
            cd /var/www/html/
            wget https://github.com/magento/magento2/archive/$MAGENTO_VERSION.tar.gz -O - | tar -xz
            cd magento2-$MAGENTO_VERSION
            composer install --prefer-dist
            ./bin/magento setup:install --backend-frontname admin --db-host 127.0.0.1 --db-prefix tnw --db-name magento --db-user mage --db-password mage --base-url http://magento-qa.box/ --language en_US --timezone America/Chicago --currency USD --admin-lastname Admin --admin-firstname Admin --admin-email admin@example.com --admin-user admin --admin-password admin123 --cleanup-database --use-rewrites 1
            ./bin/magento --version
      - run:
          name: Copy the Extension Files
          command: |
            cd /var/www/html/magento2-$MAGENTO_VERSION
            mkdir -p ./app/code/TNW
            cp -R ~/tnw_extension/* ./app/code/TNW
            ls -la ./app/code/TNW
      - run:
          name: Install the Extension
          command: |
            cd /var/www/html/magento2-$MAGENTO_VERSION
            rm -rf ./generated/*
            composer require tnw/soap-client
            ./bin/magento module:status
            ./bin/magento module:enable TNW_Salesforce TNW_SForceBusiness TNW_SForceEnterprise
            ./bin/magento setup:upgrade
      - run:
          name: Compile the Code
          command: |
            cd /var/www/html/magento2-$MAGENTO_VERSION
            ./bin/magento setup:di:compile
      - run:
          name: Installing Magento EE
          command: |
            cd /var/www/html/
            composer config -g http-basic.repo.magento.com a32f9576628eb71f11b1a381c900516c eee87cca8b50f63c9664ead0d0d93d4b
            composer create-project -s RC --repository-url=https://repo.magento.com/ magento/project-enterprise-edition magento2-ee-$MAGENTO_VERSION $MAGENTO_VERSION
            cd magento2-ee-$MAGENTO_VERSION
            ./bin/magento setup:install --backend-frontname admin --db-host 127.0.0.1 --db-prefix tnwee --db-name magento --db-user mage --db-password mage --base-url http://magento-qa.box/ --language en_US --timezone America/Chicago --currency USD --admin-lastname Admin --admin-firstname Admin --admin-email admin@example.com --admin-user admin --admin-password admin123 --cleanup-database --use-rewrites 1
            ./bin/magento --version
      - run:
          name: Copy the Extension Files
          command: |
            cd /var/www/html/magento2-ee-$MAGENTO_VERSION
            mkdir -p ./app/code/TNW
            cp -R ~/tnw_extension/* ./app/code/TNW
            ls -la ./app/code/TNW
      - run:
          name: Install the Extension
          command: |
            cd /var/www/html/magento2-ee-$MAGENTO_VERSION
            rm -rf ./generated/*
            composer require tnw/soap-client
            ./bin/magento module:status
            ./bin/magento module:enable TNW_Salesforce TNW_SForceBusiness TNW_SForceEnterprise
            ./bin/magento setup:upgrade
      - run:
          name: Compile the Code
          command: |
            cd /var/www/html/magento2-ee-$MAGENTO_VERSION
            ./bin/magento setup:di:compile
      - run:
          name: Run Magento Coding Standard
          command: |
            /var/www/html/magento-coding-standard/vendor/bin/phpcs $CIRCLE_WORKING_DIRECTORY --standard=MEQP2 --severity=10 --extensions=php,phtml
      # Need to FIX unit tests
      #- run:
      #    name: Run Unit Test
      #    command: |
      #      cd /var/www/html/magento2-$MAGENTO_VERSION
      #      ./bin/magento dev:tests:run -c'--filter=TNW' unit
  m224_php71:
    <<: *php71-base
    environment:
      MAGENTO_VERSION: "2.2.4"
  m223_php71:
    <<: *php71-base
    environment:
      MAGENTO_VERSION: "2.2.3"
  m222_php71:
    <<: *php71-base
    environment:
      MAGENTO_VERSION: "2.2.2"
  m221_php71:
    <<: *php71-base
    environment:
      MAGENTO_VERSION: "2.2.1"
  m224_php70: &php70-base
    <<: *php71-base
    docker:
      - image: circleci/php:7.0-apache-node-browsers
      - image: circleci/mysql:5.7
        environment:
          MYSQL_PASSWORD: mage
          MYSQL_USER: mage
          MYSQL_DATABASE: magento
          MYSQL_ROOT_PASSWORD: docker
    environment:
      MAGENTO_VERSION: "2.2.4"
  m223_php70:
    <<: *php70-base
    environment:
      MAGENTO_VERSION: "2.2.3"
  m222_php70:
    <<: *php70-base
    environment:
      MAGENTO_VERSION: "2.2.2"
  m221_php70:
    <<: *php70-base
    environment:
      MAGENTO_VERSION: "2.2.1"
  m225_php70:
    <<: *php70-base
    environment:
      MAGENTO_VERSION: "2.2.5"

workflows:
  version: 2

  build-test:
    jobs:
      - m225_php71:
          filters:
            branches:
              only: /.*/
      - m224_php71:
          filters:
            branches:
              only:
                - develop
                - master
                - /^hotfix*/
                - /^release*/
      - m223_php71:
          filters:
            branches:
              only:
                - develop
                - master
                - /^hotfix*/
                - /^release*/
      - m222_php71:
          filters:
            branches:
              only:
                - develop
                - master
                - /^hotfix*/
                - /^release*/
      - m221_php71:
          filters:
            branches:
              only:
                - develop
                - master
                - /^hotfix*/
                - /^release*/
      - m225_php70:
          filters:
            branches:
              only:
                - develop
                - master
                - /^hotfix*/
                - /^release*/
      - m224_php70:
          filters:
            branches:
              only:
                - develop
                - master
                - /^hotfix*/
                - /^release*/
      - m223_php70:
          filters:
            branches:
              only:
                - develop
                - master
                - /^hotfix*/
                - /^release*/
      - m222_php70:
          filters:
            branches:
              only:
                - develop
                - master
                - /^hotfix*/
                - /^release*/
      - m221_php70:
          filters:
            branches:
              only:
                - develop
                - master
                - /^hotfix*/
                - /^release*/
