<?php
// @codingStandardsIgnoreFile
?>
<div class="content">
    <h1><?php echo __('Connection Setup') ?></h1>
    <p><?php echo __('Contact your Salesforce integration or Salesforce system administrator to acquire necessary files and credentials required for this step') ?></p>
</div>
<form method="post" action="<?php echo $block->getTestConnectionUrl()?>" id="wizard_test_connection_form" class="tnw-form" autocomplete="off">
    <p class="msg" style="display:none"><span><?php echo __('Validating Powersync license') ?></span></p>
    <input class="section" name="section" style="display:none" value="tnwsforce_general" />
    <fieldset class="admin__fieldset">
        <div class="admin__field _required field-orderid">
            <label for="username" class="admin__field-label"><span><?php echo __('Username') ?></span></label>
            <div class="admin__field-control">
                <input
                    id="username"
                    class="admin__control-text"
                    type="text"
                    name="groups[salesforce][fields][username]"
                    autofocus
                    value=""
                    required=""
                    placeholder="<?php echo __('Username') ?>"/>
            </div>
        </div>
        <div class="admin__field _required field-email">
            <label for="password" class="admin__field-label"><span><?php echo __('Password') ?></span></label>
            <div class="admin__field-control">
                <input
                    id="password"
                    class="admin__control-text"
                    type="password"
                    name="groups[salesforce][fields][password]"
                    autofocus
                    value=""
                    required=""
                    placeholder="<?php echo __('Password') ?>"/>
            </div>
        </div>
        <div class="admin__field _required field-email">
            <label for="token" class="admin__field-label"><span><?php echo __('Token') ?></span></label>
            <div class="admin__field-control">
                <input
                    id="token"
                    class="admin__control-text"
                    type="password"
                    name="groups[salesforce][fields][token]"
                    autofocus
                    value=""
                    required=""
                    placeholder="<?php echo __('Token') ?>"/>
                <comment><?php echo __('Security token for your Salesforce organization') ?></comment>
            </div>

        </div>
        <div class="admin__field _required field-email">
            <label for="wsdl" class="admin__field-label"><span><?php echo __('WSDL Path') ?></span></label>
            <div class="admin__field-control">
                <input
                    id="wsdl"
                    class="admin__control-text"
                    type="text"
                    name="groups[salesforce][fields][wsdl]"
                    autofocus
                    value=""
                    required=""
                    placeholder="<?php echo __('WSDL Path') ?>"/>
                <comment><?php echo __('Path to the Enterprise WSDL file you generated from Salesforce and uploaded to Magento. Path is relative to Magento root folder.ex. app/my.wsdl.xml') ?></comment>
            </div>
        </div>
    </fieldset>
</form>
<div class="next-btn-text submit"><?php echo __('Test Connection') ?></div>
