<?php
// @codingStandardsIgnoreFile
?>
<div class="content">
    <h1><?php echo __('Salesforce Contacts') ?></h1>
    <p><?php echo __('Salesforce contact configuration settings') ?></p>
</div>
<form method="post" action id="wizard_salesforce_contacts_form" class="tnw-form" autocomplete="off">
    <input class="section" name="section" style="display:none" value="tnwsforce_customer" />
    <div class="field admin__fieldset">
        <div class="clearfix">
            <div class="field-control">
                <input id="account_name" class="checkbox" type="checkbox" name="groups[general][fields][contact_existing_account]" value="0">
            </div>
            <span class="field-label"><?php echo __('Default owner will be taken from Account') ?></span>
        </div>
        <div class="dependable-reversed admin__field">
            <?php $owners = $block->getOwners(); ?>
            <?php if (count($owners)): ?>
                <label class="admin__field-label" for="default_owner"><?php echo __('Default Owner') ?></label>
                <div class="admin__field-control">
                    <select id="default_owner" class="select admin__control-select" name="groups[general][fields][default_contact_owner]">
                        <?php foreach($owners as $group): ?>
                            <option value="<?php echo $group['value'] ?>"><?php echo $group['label'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            <?php endif; ?>
        </div>
    </div>
</form>
<div class="next-btn-text submit"><?php echo __('Continue') ?></div>
