<?php
// @codingStandardsIgnoreFile
?>
<div class="content">
    <h1><?php echo __('Magento Customer') ?></h1>
    <p><?php echo __('Magento customer configuration settings') ?></p>
</div>
<form method="post" action id="wizard_customers_form" class="tnw-form" autocomplete="off">
    <input class="section" name="section" style="display:none" value="tnwsforce_customer" />
    <div class="field">
        <input id="tnwsforce_customer_general_sync_groups" class="checkbox" type="checkbox" name="groups[general][fields][sync_groups]" value="0">
        <span><?php echo __('Only sync certain customer groups') ?></span>
        <div class="_required dependable" style="display:none">
            <label for="tnwsforce_customer_general_customer_group"><span><?php echo __('Customer Group') ?></span></label>
            <?php if (count($block->getCustomerGroups())): ?>
                <select
                    id="tnwsforce_customer_general_customer_group"
                    class="select multiselect admin__control-multiselect"
                    name="groups[general][fields][customer_group][]"
                    required=""
                    disabled="disabled"
                    multiple="multiple"
                    >
                    <?php foreach($block->getCustomerGroups() as $group): ?>
                        <option value="<?php echo $group['value'] ?>"><?php echo $group['label'] ?></option>
                    <?php endforeach; ?>
                </select>
            <?php endif; ?>
        </div>
    </div>
</form>
<div class="next-btn-text submit"><?php echo __('Continue') ?></div>
