<?php
// @codingStandardsIgnoreFile
?>
<div class="content">
    <h1><?php echo __('General Setup') ?></h1>
    <p><?php echo __('Basic settings around notification and login') ?></p>
</div>
<form method="post" action id="wizard_general_info_form" class="tnw-form" autocomplete="off">
    <input class="section" name="section" style="display:none" value="tnwsforce_general" />
    <div class="field clearfix">
        <div class="field-control">
            <input id="log_sync" class="checkbox" type="checkbox" name="groups[debug][fields][logstatus]" value="1"/>
        </div>
        <span class="field-label"><?php echo __('Capture all sync details into log file(s)') ?></span>
    </div>
    <div class="field admin__fieldset">
        <div class="clearfix">
            <div class="field-control">
                <input id="notify_sync" class="checkbox" type="checkbox" name="groups[salesforce][fields][notify_sync]" value="1"/>
            </div>
            <span class="field-label"><?php echo __('I want to be notified if synchronization fails') ?></span>
        </div>
        <div class="_required dependable admin__field" style="display:none">
            <label class="admin__field-label" for="email_sync"><span><?php echo __('Email') ?></span></label>
            <div class="admin__field-control">
                <input
                    id="email_sync"
                    class="admin__control-text"
                    type="email"
                    name="groups[salesforce][fields][email_sync]"
                    autofocus
                    value="<?php echo $block->getAdminEmail() ?>"
                    required=""
                    disabled="disabled"
                    placeholder="<?php echo __('Email') ?>"
                />
            </div>
        </div>
    </div>
</form>
<div class="next-btn-text submit"><?php echo __('Continue') ?></div>
