<?php
// @codingStandardsIgnoreFile
?>
<div class="content">
    <h1><?php echo __('Magento Websites') ?></h1>
</div>
<?php foreach ($block->getWebsites() as $website): ?>
    <div class="website">
        <div class="status-icon"></div>
        <div class="name" id="website-<?php echo $website['value'] ?>">
            <span class="website-label"><?php echo $website['label'] ?></span>
            <span class="website-error" style="display:none"></span>
        </div>
    </div>
<?php endforeach; ?>
<button class="sync-btn ui-button additional-btn"><span><?php echo __('Synchronize')?></span></button>
<div class="next-btn-text"><?php echo __('Continue') ?></div>
<script>
    var syncUrl = "<?php echo $block->getWebsiteSyncUrl() ?>";
    require([
        "jquery"
    ], function($) {
        $(document).ready(function () {
            $('button.next-step').addClass('disabled');
            var syncBtn = $('.sync-btn');
            syncBtn.removeClass('disabled').addClass('action-button');
            syncBtn.click(function () {
                var syncBtn = $(this);
                var websites = [];
                $('div.website').each(function () {
                    if ($(this).hasClass('unsynced') || !$(this).hasClass('synced')) {
                        var id = $(this).find('.name').attr('id');
                        websites.push(id.slice(8));
                        $(this).removeClass('unsynced').addClass('processed');
                        $(this).find('.website-error').hide();
                    }
                });
                if (websites.length) {
                    syncBtn.addClass('disabled');
                    $.post(
                        syncUrl,
                        {websites: websites},
                        function (response) {
                            for (var i= 0; i < response.websites.length; i++) {
                                var website = $('#website-' + response.websites[i].id);
                                if (typeof website !== "undefined") {
                                    website.parent('div.website')
                                        .removeClass('unsynced processed')
                                        .addClass(response.websites[i].status);
                                    website.find('.website-error').html(response.websites[i].errorMsg);
                                }
                            }
                            var failedWebsites = false;
                            $('div.website').each(function () {
                                if ($(this).hasClass('unsynced')) {
                                    failedWebsites = true;
                                    $(this).find('.website-error').show();
                                }
                            });
                            if (!failedWebsites) {
                                $('button.next-step').removeClass('disabled').addClass('action-button');
                            }
                            syncBtn.removeClass('disabled');
                        },
                        'json'
                    );
                }
            });
        });
        $(document).ajaxComplete(function() {
            if (!$('button.next-step').hasClass('disabled')) {
                $('.sync-btn').removeClass('action-button').addClass('disabled');
            }
        });
    });
</script>
