<?php
declare(strict_types=1);
/**
 * @see \TNW\Salesforce\Controller\Adminhtml\System\Config\Testconnection
 */

$urlr = $block->getAjaxUrl() ;
?>

<div class="actions actions-test-salesforce-connection"
     data-mage-init='{"TNW_Salesforce/js/connection":{"url": "<?php echo $block->getAjaxUrl()?>",
        "type": "<?php echo $block->getFormId() ?>",
        "successMessage": "<?php echo __('Connection successful!') ?>",
        "inProgressMessage": "<?php echo __('Testing...') ?>"
        }}'>
    <button disabled type="button" class="action test-connection action-primary">
        <span><?php echo $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
    <div class="message-box connection-test-status"><div class="connection-test-status-label"></div></div>
</div>

<script type="text/x-magento-init">
    {
        "#tnwsforce_general_salesforce_wsdl": {
            "TNW_Salesforce/js/upload": {
                "ajaxUrl": "<?= $block->getAjaxUrl() ?>"
            }
        }
    }
</script>
